"""Initial professional structure

Revision ID: 8fc1dfe4ce36
Revises: 
Create Date: 2026-06-25 18:03:05.389840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc1dfe4ce36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.alter_column('admin_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('plan_setup',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.alter_column('plan_setup',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('admin_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
